<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	<RootNamespace>CleanArchitecture</RootNamespace>
	<AssemblyName>CleanArchitecture.Infrastructure</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
	<PackageReference Include="AspNetCore.HealthChecks.UI.Client" Version="9.0.0" />
	<PackageReference Include="Lightsoft.ActiveDirectory" Version="0.0.0.16" />
	<PackageReference Include="Lightsoft.AspNetCore.Extensions" Version="0.0.0.52" />
	<PackageReference Include="Lightsoft.AspNetCore.Modularity" Version="0.0.0.4" />
	<PackageReference Include="Lightsoft.EntityFrameworkCore" Version="0.0.0.15" />
	<PackageReference Include="Lightsoft.Identity.EntityFrameworkCore" Version="0.0.0.23" />
	<PackageReference Include="Lightsoft.Serilog" Version="0.0.0.9" />
  </ItemGroup>

  <ItemGroup>
	<PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="9.0.5" />
	<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.5" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Application\Application.csproj" />
  </ItemGroup>

</Project>
