<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	<RootNamespace>CleanArchitecture</RootNamespace>
	<AssemblyName>CleanArchitecture.Shared</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
	<PackageReference Include="FluentValidation" />
	<PackageReference Include="Lightsoft.Identity" />
	<PackageReference Include="Mapster" />
	<PackageReference Include="Lightsoft.Ddd.Core" />
	<PackageReference Include="Lightsoft.Extensions" />
	<PackageReference Include="Lightsoft.FileGenerator" />
	<PackageReference Include="Lightsoft.Result" />
  </ItemGroup>

</Project>
