<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
	<SatelliteResourceLanguages>en</SatelliteResourceLanguages>
	<RootNamespace>CleanArchitecture</RootNamespace>
	<AssemblyName>CleanArchitecture.WebApi</AssemblyName>
	<UserSecretsId>6bfa1f49-26a0-487e-93ae-9201dcad2491</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
	<PackageReference Include="AspNetCore.HealthChecks.UI.Client" Version="9.0.0" />
	<PackageReference Include="FluentValidation.AspNetCore" Version="11.3.0" />
	<PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="11.11.0" />
	<PackageReference Include="Lightsoft.AspNetCore.Swagger" Version="0.0.0.11" />
	<PackageReference Include="Lightsoft.Serilog" Version="0.0.0.8" />
	<PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.21.2" />
	<PackageReference Include="Spectre.Console" Version="0.50.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Authorization\Authorization.csproj" />
    <ProjectReference Include="..\Infrastructure\Infrastructure.csproj" />
  </ItemGroup>

</Project>
